### ISSUE TITLE
Do we have the script to reproduce figure 5?

### ISSUE THREAD

**Issue by jeremyyx** [csl-ajou/DeepPlan#2]
Hello, I am very interested in your work and particularly intrigued by the motivation for analysis. I was wondering if you have any relevant analysis scripts available for Figure 5?

**Comment by JinuJeong** [comment]
I'm sorry, we don't have scripts for Figure 5. Instead, you can utilize `plan.py` to get the data. It includes a profiling phase that measures runtime performance such as loading time, DHA execution, and GPU in-memory execution time. As a result, you will be able to extract the relevant data for Figure 5 from the `plan.py`.
